apiVersion: v1
kind: Secret
metadata:
  name: meeting-scheduler-secrets
  namespace: robert
type: Opaque
stringData:
  GMAIL_ADDRESS: "eric.lysenko1@gmail.com"
  GMAIL_APP_PASSWORD: "prwi kzho gznc gkak"
  DATABASE_URL: "postgresql://robert:yR1ii1XfXIYRuVgj@robert-postgresql.robert.svc.cluster.local:5432/robert"
