apiVersion: v1
kind: Service
metadata:
  name: finance-personal-backend
  namespace: finance-personal
spec:
  selector:
    app: finance-personal-backend
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: finance-personal-frontend
  namespace: finance-personal
spec:
  selector:
    app: finance-personal-frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30091
  type: NodePort
