apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: robert

resources:
- pvc.yaml
- deployment.yaml
- service.yaml
# Run after deployment is ready:
# - model-pull-job.yaml

commonLabels:
  app.kubernetes.io/name: ollama
  app.kubernetes.io/component: trigger-llm
  app.kubernetes.io/part-of: ccpm
