apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ccpm-infra
  namespace: robert
  labels:
    app: ccpm-infra
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: ccpm-infra.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ccpm-infra
                port:
                  number: 80
