apiVersion: v1
kind: Service
metadata:
  name: ccpm-infra
  namespace: robert
  labels:
    app: ccpm-infra
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: ccpm-infra
---
apiVersion: v1
kind: Service
metadata:
  name: ccpm-infra-nodeport
  namespace: robert
  labels:
    app: ccpm-infra
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30888
      protocol: TCP
      name: http
  selector:
    app: ccpm-infra
